### ISSUE TITLE
Information about past ESMValTool Workshop

### ISSUE THREAD

**Issue by TomasTorsvik** [ESMValGroup/Community#103]
Hi,

we recently had a ESMValTool user workshop at the University of Bergen, supported by NICEST2, INES-interim and KeyCLIM projects. The presentations are available from the workshop webpage:
https://nordicesmhub.github.io/esmvaltool-workshop
and have been published on zenodo: https://zenodo.org/record/7993930

Is this an event that you would like to have included in the list of training events in the README.md file? Should I add it there even though it is a past event?

**Comment by bouweandela** [comment]
Yes, that would be great. Like that, other people may also benefit from the training material and we can show to funders that we do outreach and are having an impact as a community. If you haven't done so already, could you [add a license](https://creativecommons.org/share-your-work/) to the training material so others can re-use it to make new trainings?
